
from app import app, db
from app.models.course import Course

def add_courses():
    courses = [
        {"title": "Introduction to Python", "description": "Learn Python programming basics. voluptatem saepe ad a nesciunt hic architecto quia obcaecati, sit ipsa eaque laboriosam fugiat sunt error sed modi sapiente sequi. Cum vero tempora quasi ut corrupti ipsa sed, fugit, hic minima ad eveniet modi dicta! Porro corporis, accusamus commodi repellendus at laborum fugit quisquam dolor assumenda hic sint! Perferendis nam repudiandae ipsam eius consequuntur, eos tempora facere id dolorem? Molestias eligendi at qui id unde doloribus doloremque nisi distinctio aliquam nulla maxime, expedita deleniti fugit voluptate recusandae! Sequi, sit aperiam fuga minus accusantium facilis laboriosam laudantium repellat aliquam minima necessitatibus assumenda dolor! Illum obcaecati delectus minus sequi commodi fuga impedit distinctio eligendi assumenda doloremque natus blanditiis debitis corporis ratione, architecto laudantium a dignissimos iure quis quo sed. Dolores.", "fee": 49.99},
        {"title": "Web Development with Flask", "description": "Build web applications with Flask. voluptatem saepe ad a nesciunt hic architecto quia obcaecati, sit ipsa eaque laboriosam fugiat sunt error sed modi sapiente sequi. Cum vero tempora quasi ut corrupti ipsa sed, fugit, hic minima ad eveniet modi dicta! Porro corporis, accusamus commodi repellendus at laborum fugit quisquam dolor assumenda hic sint! Perferendis nam repudiandae ipsam eius consequuntur, eos tempora facere id dolorem? Molestias eligendi at qui id unde doloribus doloremque nisi distinctio aliquam nulla maxime, expedita deleniti fugit voluptate recusandae! Sequi, sit aperiam fuga minus accusantium facilis laboriosam laudantium repellat aliquam minima necessitatibus assumenda dolor! Illum obcaecati delectus minus sequi commodi fuga impedit distinctio eligendi assumenda doloremque natus blanditiis debitis corporis ratione, architecto laudantium a dignissimos iure quis quo sed. Dolores.", "fee": 59.99},
        {"title": "Data Analysis with Pandas", "description": "Explore data analysis techniques with Pandas. voluptatem saepe ad a nesciunt hic architecto quia obcaecati, sit ipsa eaque laboriosam fugiat sunt error sed modi sapiente sequi. Cum vero tempora quasi ut corrupti ipsa sed, fugit, hic minima ad eveniet modi dicta! Porro corporis, accusamus commodi repellendus at laborum fugit quisquam dolor assumenda hic sint! Perferendis nam repudiandae ipsam eius consequuntur, eos tempora facere id dolorem? Molestias eligendi at qui id unde doloribus doloremque nisi distinctio aliquam nulla maxime, expedita deleniti fugit voluptate recusandae! Sequi, sit aperiam fuga minus accusantium facilis laboriosam laudantium repellat aliquam minima necessitatibus assumenda dolor! Illum obcaecati delectus minus sequi commodi fuga impedit distinctio eligendi assumenda doloremque natus blanditiis debitis corporis ratione, architecto laudantium a dignissimos iure quis quo sed. Dolores.", "fee": 69.99},
        {"title": "Machine Learning Fundamentals", "description": "Introduction to machine learning concepts. voluptatem saepe ad a nesciunt hic architecto quia obcaecati, sit ipsa eaque laboriosam fugiat sunt error sed modi sapiente sequi. Cum vero tempora quasi ut corrupti ipsa sed, fugit, hic minima ad eveniet modi dicta! Porro corporis, accusamus commodi repellendus at laborum fugit quisquam dolor assumenda hic sint! Perferendis nam repudiandae ipsam eius consequuntur, eos tempora facere id dolorem? Molestias eligendi at qui id unde doloribus doloremque nisi distinctio aliquam nulla maxime, expedita deleniti fugit voluptate recusandae! Sequi, sit aperiam fuga minus accusantium facilis laboriosam laudantium repellat aliquam minima necessitatibus assumenda dolor! Illum obcaecati delectus minus sequi commodi fuga impedit distinctio eligendi assumenda doloremque natus blanditiis debitis corporis ratione, architecto laudantium a dignissimos iure quis quo sed. Dolores.", "fee": 79.99},
        {"title": "JavaScript Essentials", "description": "Fundamentals of JavaScript programming. voluptatem saepe ad a nesciunt hic architecto quia obcaecati, sit ipsa eaque laboriosam fugiat sunt error sed modi sapiente sequi. Cum vero tempora quasi minus sequi commodi fuga impedit distinctio eligendi assumenda doloremque natus blanditiis debitis corporis ratione, architecto laudantium a dignissimos iure quis quo sed. Dolores.", "fee": 39.99},
        {"title": "React for Beginners", "description": "Get started with React framework. voluptatem saepe ad a nesciunt hic architecto quia obcaecati, sit ipsa eaque laboriosam fugiat sunt error sed modi sapiente sequi. Cum vero tempora quasi ut corruptictus minus sequi commodi fuga impedit distinctio eligendi assumenda doloremque natus blanditiis debitis corporis ratione, architecto laudantium a dignissimos iure quis quo sed. Dolores.", "fee": 49.99},
        {"title": "Advanced SQL Techniques", "description": "Master advanced SQL querying. voluptatem saepe ad a nesciunt hic architecto quia obcaecati, sit inus sequi commodi fuga impedit distinctio eligendi assumenda doloremque natus blanditiis debitis corporis ratione, architecto laudantium a dignissimos iure quis quo sed. Dolores.", "fee": 59.99},
        {"title": "Cloud Computing Basics", "description": "Introduction to cloud computing platforms. voluptatem saepe ad a nesciunt hic architecto quia obcaecris ratione, architecto laudantium a dignissimos iure quis quo sed. Dolores.", "fee": 69.99},
        {"title": "Ethical Hacking Fundamentals", "description": "Learn ethical hacking techniques. voluptatem saepe ad a nesciunt hic architecto quia obcaecati, sit ipsa eaque laboriosam fugiat sunt error sed modi sapiente sequi. Cum vero tempora quasi ut corus minus sequi commodi fuga impedit distinctio eligendi assumenda doloremque natus blanditiis debitis corporis ratione, architecto laudantium a dignissimos iure quis quo sed. Dolores.", "fee": 79.99},
        {"title": "Digital Marketing Strategies", "description": "Explore digital marketing tactics. voluptatem saepe ad a nesciunt hic architecto quia obcaecati, sit ipsa eaque laboriosam fugiat sunt error sed modi sapiente sequi. Cum vero tempora quasi ut corrrporis ratione, architecto laudantium a dignissimos iure quis quo sed. Dolores.", "fee": 49.99}
    ]

    for course_data in courses:
        course = Course(**course_data)
        db.session.add(course)

    db.session.commit()

if __name__ == '__main__':
    with app.app_context():
        add_courses()
    print("Courses added successfully!")
